baseURL = 'https://nyashbox.cc/'
languageCode = 'en-us'
title = 'nyashbox.cc'
theme = 'plague'

[params]
siteHeaderText = "nyashbox.cc"
colors = "default"

[params.hcard]
    fullName = "nyashbox"
    nickname = "nyashbox"
    showLocation = false 

[caches]
  [caches.images]
    dir = ':cacheDir/images'
